// DON'T EDIT *** generated by ormgen *** DON'T EDIT
package store

import (
	"time"
	"github.com/gofrs/uuid"
)


type User struct { 
ID int64`json:"id"`
Updated time.Time`json:"updated"`
Name string`json:"name"`
FirstName string`json:"firstName"`
UserType *UserType`json:"userType"`
}

type UserType struct { 
ID int64`json:"id"`
Name string`json:"name"`
}

